twitter-to-kafka-service:
  tweets-keywords:
    - Java
    - Spring
    - Microservices
    - Kafka
    - Elasticsearch
    - PostgreSQL

  mock:
    delay: 1000
    min-text-length: 10
    max-text-length: 50

  retry:
    initial-interval-ms: 1000
    max-interval-ms: 10000
    multiplier: 2.0
    max-attempts: 3

  kafka:
    twitter-topic:
      name: twitter-topic
      partitions: 3
      replicas: 1

spring:
  kafka:
    bootstrap-servers:
      - localhost:19092
    admin:
      properties:
        auto-create: false
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      compression-type: snappy
      batch-size: 16384
      retries: 5
      properties:
        batch-size:
          boost-factor: 10
        schema:
          registry:
            url: http://localhost:8081
#      - localhost:29092
#      - localhost:39092

logging:
  level:
    com.training: DEBUG