twitter-to-kafka-service:
  tweets-keywords:
    - Java
    - Spring
    - Microservices
    - Kafka
    - Elasticsearch
    - PostgreSQL
  mock:
    delay: 1000
    min-text-length: 10
    max-text-length: 50


